rdcontacts/config/routes.rb
Rails.application.routes.draw do
  root             'base#index'
  get  'about'     => 'base#about'
  get  'login'     => 'sessions#new'
  post 'login'     => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'signup'     =>  'users#new'

  resources :users do
    resources :contacts
    resources :custom_fields
  end

end

rdcontacts/app/models/contact.rb
class Contact < ActiveRecord::Base
  # Relations
  belongs_to :user
  has_many :custom_field_info
  accepts_nested_attributes_for :custom_field_info

  # Validations
  validates :name, presence: true, length: { maximum: 50 }
  validates :lastname, length: { maximum: 50 }

  validates :email, presence: true, length: { maximum: 300 },
                    uniqueness: { case_sensitive: false },
                    format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
end

rdcontacts/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :session_right_user, only: [:edit, :update, :index, :show]

  def index
    @user = User.find(params[:user_id])
    @contact = @user.contact.all
    @page_title = 'All Contacts'

    @custom_f = @user.custom_field
    # Get field just if there's a contact
    unless @contact.nil?
      @custom_field_info = CustomFieldInfo.all
    end

  end

  def show
    @user = User.find(params[:user_id])
    @contact = @user.contact.find(params[:id])
    @page_title = 'Contact'
  end

  def new
    @user = User.find(params[:user_id])
    @contact = @user.contact.new
    @form_params = { head_title: "Add a new contact", submit_message: "Add", form_path: user_contacts_path, form_method: :post }
    @page_title = 'New Contact'

    @custom_f = @user.custom_field
    # Get field just if there's a contact
    unless @contact.nil?
      @custom_field_info = @contact.custom_field_info
    end

    render 'layouts/_contacts_form'
  end

  def edit
    @user = User.find(params[:user_id])
    @contact = @user.contact.find(params[:id])
    @form_params = { head_title: "Edit contact", submit_message: "Edit",
                     form_path: user_contact_path, form_method: :patch }
    @page_title = 'Edit Contact'

    @custom_f = @user.custom_field
    # Get field just if there's a contact
    unless @contact.nil?
      @custom_field_info = @contact.custom_field_info
    end

    render 'layouts/_contacts_form'
  end

  def create
    @user = User.find(params[:user_id])
    @contact = @user.contact.build(contact_params)

    # Prototype of how custom fields info should be edited
    #@custom_f = @user.custom_field
    # Get field just if there's a contact
    #unless @contact.nil?
    #  @custom_field_info = @contact.custom_field_info
    #end

    if @contact.save
      redirect_to user_contacts_path(@user)
    else
      @form_params = { head_title: "Add a new contact", submit_message: "Add",
                       form_path: user_contacts_path, form_method: :post }
      @page_title = 'New Contact'

      render 'layouts/_contacts_form'
    end
  end

  def update
    @user = User.find(params[:user_id])
    @contact = @user.contact.find(params[:id])

    # Prototype of how custom fields info should be edited
    #@custom_f = @user.custom_field
    # Get field just if there's a contact
    #unless @contact.nil?
    #  @custom_field_info = @contact.custom_field_info
    #end

    if @contact.update_attributes(contact_params)
      redirect_to user_contacts_path(@user)
    else
      @form_params = { head_title: "Edit contact", submit_message: "Edit",
                       form_path: user_contact_path, form_method: :patch }
      @page_title = 'Edit Contact'

      render 'layouts/_contacts_form'
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @contact = @user.contact.find(params[:id])
    @contact.destroy
    redirect_to user_contacts_path(@user)
  end

  private
    def contact_params
      params.require(:contact).permit(:name, :lastname, :email)
    end
end

rdcontacts/app/helpers/contacts_helper.rb
module ContactsHelper
end

rdcontacts/app/views/contacts/index.html.erb
<div class="center jumbotron">

  <h1>Your Contacts</h1>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <table class="table">
        <thead>
          <th>Name</th>
          <th>Lastname</th>
          <th>Email</th>
            <% @custom_f.each do |cf| %>
              <th> <%= cf.name %> </th>
            <% end %>
        </thead>
        <tbody>
          <% @contact.each do |co| %>
          <tr>
              <td> <%= co.name %> </td>
              <td> <%= co.lastname %> </td>
              <td> <%= co.email %> </td>
            <% @custom_f.each do |cf| %>
                <% @custom_field_info.each do |cfi| %>
                  <% if cfi.contact_id == co.id && cfi.custom_field_id == cf.id %>
                      <td> <%= cfi.data %> </td>
                  <% end %>
                <% end %>
            <% end %>
              <td> <%= link_to "Edit", edit_user_contact_path(session_logged_user.id, co.id) %> </td>
              <td> <%= link_to "Delete", user_contact_path(session_logged_user.id, co.id), method: "delete", data: { confirm: "Are you sure?" } %> </td>
          </tr>
          <% end %>
        </tbody>
      </table>
        <p><%= link_to "Add new contact", new_user_contact_path(session_logged_user), class: "btn btn-lg btn-success" %></p>
    </div>
  </div>
</div>